name: Creo el script

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecuto un script
        run: echo "Link Start"
            
      - name: pwd
        run: pwd
       
      - name: cn
        run: ls /home/runner/work/Admredes-Nicolas-Paz-6-11/Admredes-Nicolas-Paz-6-11
        
      - name: hello
        run: mkdir start
        
      - name: nsh
        cp linkstart.txt /home/runner/work/Admredes-Nicolas-Paz-6-11/Admredes-Nicolas-Paz-6-11/start
        
        
        
